# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fmTWi3Q2HSxXPUTgwR68vvrn5kZzj_qA
"""

import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("titanic.csv")
df.head()
df["Survived"].plot()

df = pd.read_csv('titanic.csv')

qtd_mulheres = len(df[df['Sex'] == 'female'])
qtd_homens = len(df[df['Sex'] == 'male'])

qtd_homens_falecidos= len(df[(df['Sex'] == 'male') & (df['Survived'] == 0)])
qtd_mulheres_falecidas = len(df[(df['Sex'] == 'female') & (df['Survived'] == 0)])

data = pd.DataFrame({
    'Sexo': ['Mulheres', 'Homens', 'Mulheres falecidas', 'Homens falecidos'],
    'Quantidade': [qtd_mulheres, qtd_homens, qtd_mulheres_falecidas, qtd_homens_falecidos]
})

data.plot(x = 'Sexo', y = 'Quantidade', kind='bar')

plt.xlabel('Sexo')
plt.ylabel('Quantidade')
plt.title('Quantidade de Homens e Mulheres no Titanic')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt


df = pd.read_csv('titanic.csv')


resultado = df.groupby(['Sex', 'Survived']).size().unstack(fill_value=0)


resultado.columns = ['Falecidos', 'Sobreviventes']


data = pd.DataFrame({
    'Sexo': ['Mulheres', 'Homens', 'Mulheres falecidas', 'Homens falecidos'],
    'Quantidade': [
        resultado.loc['female', 'Sobreviventes'],
        resultado.loc['male', 'Sobreviventes'],
        resultado.loc['female', 'Falecidos'],
        resultado.loc['male', 'Falecidos'],
    ]
})


data.plot(x='Sexo', y='Quantidade', kind='bar')

plt.xlabel('Sexo')
plt.ylabel('Quantidade')
plt.title('Quantidade de Homens e Mulheres no Titanic')
plt.show()

df = pd.read_csv('titanic.csv')


resultado = df.groupby(['Sex', 'Survived']).size().unstack(fill_value=0)


resultado.columns = ['Falecidos', 'Sobreviventes']


data = pd.DataFrame({
    'Sexo': ['Mulheres sobreviventes', 'Homens sobreviventes', 'Mulheres falecidas', 'Homens falecidos'],
    'Quantidade': [
        resultado.loc['female', 'Sobreviventes'],
        resultado.loc['male', 'Sobreviventes'],
        resultado.loc['female', 'Falecidos'],
        resultado.loc['male', 'Falecidos'],
    ]
})

total = data['Quantidade'].sum()

data['Porcentagem'] = (data['Quantidade'] / total) * 100

data.plot.pie(y='Porcentagem', labels=data['Sexo'], autopct='%1.1f%%', startangle=90)

plt.ylabel('')
plt.title('Porcentagem de Homens e Mulheres no Titanic')
plt.show()

df = pd.read_csv('titanic.csv')


resultado = df.groupby(['Sex', 'Survived']).size().unstack(fill_value=0)


resultado.columns = ['Falecidos', 'Sobreviventes']


data = pd.DataFrame({
    'Sexo': ['Mulheres sobreviventes', 'Homens sobreviventes'],
    'Quantidade': [
        resultado.loc['female', 'Sobreviventes'],
        resultado.loc['male', 'Sobreviventes'],
    ]
})

total = data['Quantidade'].sum()

data['Porcentagem'] = (data['Quantidade'] / total) * 100

data.plot.pie(y='Porcentagem', labels=data['Sexo'], autopct='%1.1f%%', startangle=90)

plt.ylabel('')
plt.title('Porcentagem de Homens e Mulheres no Titanic')
plt.show()

df = pd.read_csv('titanic.csv')


resultado = df.groupby(['Sex', 'Survived']).size().unstack(fill_value=0)


resultado.columns = ['Falecidos', 'Sobreviventes']


data = pd.DataFrame({
    'Sexo': ['Mulheres sobreviventes', 'Homens sobreviventes', 'Mulheres falecidas', 'Homens falecidos'],
    'Quantidade': [
        resultado.loc['female', 'Sobreviventes'],
        resultado.loc['male', 'Sobreviventes'],
        resultado.loc['female', 'Falecidos'],
        resultado.loc['male', 'Falecidos'],
    ]
})

total = data['Quantidade'].sum()

data['Porcentagem'] = (data['Quantidade'] / total) * 100

data.plot.pie(y='Porcentagem', labels=data['Sexo'], autopct='%1.1f%%', startangle=90)

plt.ylabel('')
plt.title('Porcentagem de Homens e Mulheres no Titanic')
plt.show()