services:
  dashboard:
    build:
      context: ./workdir
      dockerfile: Dockerfile
    container_name: streamlit_service
    ports:
      - 8501:8501
    volumes:
      - ./workdir/app:/app #nome e caminho do volume criado para persistência dos dados
      - ../data:/data